#!/usr/bin/env python
# Build: git clone -b 4.3 https://github.com/godotengine/godot-cpp && scons platform=macos
import os

env = SConscript("godot-cpp/SConstruct")
root = Dir("#../..").abspath
env.Append(CPPPATH=["src", os.path.join(root, "Sources/CTactileHeaders/include")])
bin_dir = os.environ.get("TACTILE_BIN", os.path.join(root, ".build/out/Products/Release"))
env.Append(LIBPATH=[bin_dir], LIBS=["CTactile"], LINKFLAGS=["-Wl,-rpath,@loader_path"])
sources = Glob("src/*.cpp")
library = env.SharedLibrary("demo/bin/libtactile_godot{}{}".format(env["suffix"], env["SHLIBSUFFIX"]), source=sources)
Default(library)
